/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NarrativePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ExternalLink = {
  _type: "externalLink";
  label?: string;
  url?: string;
};

export type ImpactHighlight = {
  _type: "impactHighlight";
  body?: string;
  metricValue?: string;
  metricDescription?: string;
};

export type TimePeriod = {
  _type: "timePeriod";
  startDate?: string;
  endDate?: string;
};

export type Language = {
  _id: string;
  _type: "language";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  proficiency?: "native" | "fluent" | "professional" | "conversational";
};

export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  skills?: Array<string>;
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  issuer?: string;
  location?: string;
  issuedAt?: string;
  credentialId?: string;
  verificationUrl?: string;
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  publisher?: string;
  location?: string;
  category?: "conference" | "journal" | "chapter" | "article";
  publishedAt?: string;
  summary?: string;
  citation?: string;
  links?: Array<{
    _key: string;
  } & ExternalLink>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  role?: string;
  objective?: string;
  summary?: NarrativePortableText;
  period?: TimePeriod;
  status?: "planned" | "inProgress" | "completed";
  highlights?: Array<{
    _key: string;
  } & ImpactHighlight>;
  technologies?: Array<string>;
  links?: Array<{
    _key: string;
  } & ExternalLink>;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  degree?: string;
  institution?: string;
  location?: string;
  studyType?: "fullTime" | "partTime" | "distance";
  period?: TimePeriod;
  classStanding?: string;
  modules?: Array<string>;
  summary?: NarrativePortableText;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?: string;
  organization?: string;
  location?: string;
  employmentType?: "fullTime" | "partTime" | "contract" | "internship";
  industryFocus?: string;
  summary?: NarrativePortableText;
  period?: TimePeriod;
  engagementStatus?: "current" | "completed";
  highlights?: Array<{
    _key: string;
  } & ImpactHighlight>;
  tooling?: Array<string>;
};

export type Resume = {
  _id: string;
  _type: "resume";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  headline?: string;
  location?: string;
  summary?: NarrativePortableText;
  experiences?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "experience";
  }>;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
  education?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "education";
  }>;
  publications?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "publication";
  }>;
  certifications?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "certification";
  }>;
  skillCategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skillCategory";
  }>;
  languages?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "language";
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = NarrativePortableText | ExternalLink | ImpactHighlight | TimePeriod | Language | SkillCategory | Certification | Publication | Project | Education | Experience | Resume | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: resumeQuery
// Query: *[_type == "resume"][0]{	_id,	fullName,	headline,	location,	summary,	experiences[]->{		_id,		role,		organization,		location,		employmentType,		industryFocus,		summary,		period,		engagementStatus,		highlights,		tooling	},	projects[]->{		_id,		title,		role,		objective,		summary,		period,		status,		highlights,		technologies,		links	},	education[]->{		_id,		degree,		institution,		location,		studyType,		period,		classStanding,		modules,		summary	},	publications[]->{		_id,		title,		publisher,		location,		category,		publishedAt,		summary,		citation,		links	},	certifications[]->{		_id,		name,		issuer,		location,		issuedAt,		credentialId,		verificationUrl	},	skillCategories[]->{		_id,		label,		skills	},	languages[]->{		_id,		name,		proficiency	}}
export type ResumeQueryResult = {
  _id: string;
  fullName: string | null;
  headline: string | null;
  location: string | null;
  summary: NarrativePortableText | null;
  experiences: Array<{
    _id: string;
    role: string | null;
    organization: string | null;
    location: string | null;
    employmentType: "contract" | "fullTime" | "internship" | "partTime" | null;
    industryFocus: string | null;
    summary: NarrativePortableText | null;
    period: TimePeriod | null;
    engagementStatus: "completed" | "current" | null;
    highlights: Array<{
      _key: string;
    } & ImpactHighlight> | null;
    tooling: Array<string> | null;
  }> | null;
  projects: Array<{
    _id: string;
    title: string | null;
    role: string | null;
    objective: string | null;
    summary: NarrativePortableText | null;
    period: TimePeriod | null;
    status: "completed" | "inProgress" | "planned" | null;
    highlights: Array<{
      _key: string;
    } & ImpactHighlight> | null;
    technologies: Array<string> | null;
    links: Array<{
      _key: string;
    } & ExternalLink> | null;
  }> | null;
  education: Array<{
    _id: string;
    degree: string | null;
    institution: string | null;
    location: string | null;
    studyType: "distance" | "fullTime" | "partTime" | null;
    period: TimePeriod | null;
    classStanding: string | null;
    modules: Array<string> | null;
    summary: NarrativePortableText | null;
  }> | null;
  publications: Array<{
    _id: string;
    title: string | null;
    publisher: string | null;
    location: string | null;
    category: "article" | "chapter" | "conference" | "journal" | null;
    publishedAt: string | null;
    summary: string | null;
    citation: string | null;
    links: Array<{
      _key: string;
    } & ExternalLink> | null;
  }> | null;
  certifications: Array<{
    _id: string;
    name: string | null;
    issuer: string | null;
    location: string | null;
    issuedAt: string | null;
    credentialId: string | null;
    verificationUrl: string | null;
  }> | null;
  skillCategories: Array<{
    _id: string;
    label: string | null;
    skills: Array<string> | null;
  }> | null;
  languages: Array<{
    _id: string;
    name: string | null;
    proficiency: "conversational" | "fluent" | "native" | "professional" | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == \"resume\"][0]{\n\t_id,\n\tfullName,\n\theadline,\n\tlocation,\n\tsummary,\n\texperiences[]->{\n\t\t_id,\n\t\trole,\n\t\torganization,\n\t\tlocation,\n\t\temploymentType,\n\t\tindustryFocus,\n\t\tsummary,\n\t\tperiod,\n\t\tengagementStatus,\n\t\thighlights,\n\t\ttooling\n\t},\n\tprojects[]->{\n\t\t_id,\n\t\ttitle,\n\t\trole,\n\t\tobjective,\n\t\tsummary,\n\t\tperiod,\n\t\tstatus,\n\t\thighlights,\n\t\ttechnologies,\n\t\tlinks\n\t},\n\teducation[]->{\n\t\t_id,\n\t\tdegree,\n\t\tinstitution,\n\t\tlocation,\n\t\tstudyType,\n\t\tperiod,\n\t\tclassStanding,\n\t\tmodules,\n\t\tsummary\n\t},\n\tpublications[]->{\n\t\t_id,\n\t\ttitle,\n\t\tpublisher,\n\t\tlocation,\n\t\tcategory,\n\t\tpublishedAt,\n\t\tsummary,\n\t\tcitation,\n\t\tlinks\n\t},\n\tcertifications[]->{\n\t\t_id,\n\t\tname,\n\t\tissuer,\n\t\tlocation,\n\t\tissuedAt,\n\t\tcredentialId,\n\t\tverificationUrl\n\t},\n\tskillCategories[]->{\n\t\t_id,\n\t\tlabel,\n\t\tskills\n\t},\n\tlanguages[]->{\n\t\t_id,\n\t\tname,\n\t\tproficiency\n\t}\n}": ResumeQueryResult;
  }
}
